### ISSUE TITLE
feat: unit tests for Deposit and withdrawal functionalities.

### ISSUE THREAD

**Issue by machuwey** [StrapexLabs/strapex#5]
Write a complete and an extensive set of unit-tests for the strapex contracts.
Scope of the tests: Deposit and withdrawal functionalities.

> [!NOTE]  
> As this contract will hold users funds it is highly important that  the test cover all possible edge cases and scenarios.

Some of examples of cairo unit tests implemented in other repos: 
- [ZkRamp](https://github.com/keep-starknet-strange/zkramp/blob/main/contracts/src/contracts/ramps/revolut/revolut_test.cairo)

Some interesting resources to learn about cairo testing:
 -[ Testing Cairo Programs](https://www.youtube.com/watch?v=FwtvBjJi4Bg&t=1949s&ab_channel=HorusLabs)

# Instructions to apply
1. Introduce yourself, tell about your background, etc.
2. Describe shortly how you plan to tackle the issue

**Comment by jsandinoDev** [comment]
Hi @machuwey  is this issue open to collaborators?

**Comment by martinvibes** [comment]
holla @machuwey would like to workon this one

**Comment by NueloSE** [comment]
@machuwey I would like to work on this task kindly assign. I have experience in writing smart contract and writing test for these contracts

**Comment by NueloSE** [comment]
I'd like to handle this task.

**Comment by Akshola00** [comment]
hi mi shola a smat contract dev, completed starklings and a starnet base camp, can I work on this issue 
I would efficiently write test the function testing all state changing events and emitted events in the function
please assignthis to me

**Comment by ShantelPeters** [comment]
Could I take over this issue?

**Comment by manlikeHB** [comment]
Hi, I am a Cairo developer with great experience contributing to lots of other projects. I would love to work on this.

I'll ensure all edge cases are covered and the test are passing

**Comment by jsandinoDev** [comment]
Hi  I'm a full-stack developer from Costa Rica and member of Dojo coding. I've worked on projects using React, Solidity, Cairo, and blockchain tools. My skills in both front-end and back-end development allow me to build scalable and secure solutions for web3 ecosystems.

For this issue I will undertand the current strapex contracts then see the examples of ZkRamp and create the full unit test set

**Comment by SoarinSkySagar** [comment]
May I work on this issue @machuwey ?

My background: I am a web3 developer with 2 years of experience and a regular contributor at https://github.com/keep-starknet-strange. I have been solving issues related to cairo for the past 2 months and I'm pretty confident that I can resolve this issue too.

My approach: I will go through the issues of ZkRamp and introduce unit tests to cover most of the edge cases

eta: 4 days

**Comment by ryzen-xp** [comment]
Hi, I am proficient Blockchain developer  expert in Cairo , Rust and Solidity.  and also in web development.
I will write comprehensive unit tests for the Strapex contracts, covering edge cases and all possible scenarios, using Cairo testing frameworks and ensuring security by simulating various user interactions and failure conditions.
please /assign me this issue

**Comment by martinvibes** [comment]
Can I take care of this issue?
i'm a frontend dev and a blockchain dev kindly assign :)

**Comment by coxmars** [comment]
Hi @machuwey, I'm a software developer with 2+ years of experience, working with backend technologies like Cairo and frontend with React/NextJS. I’m also a member of the Dojo Coding community and have contributed to Cairo VM Go, Cairo Lints, and more. Currently, I’m developing on-chain games at ByteBuildersLabs using the Dojo framework.

This is my approach:

- I will review the project's structure to ensure I understand all the logic before I continue with the tests.
- Then, I’m going to add all unit test related and I will consider all possible edge cases.
- Finally, I will apply a deep testing session to validate all is working fine.

ET: I will send a PR in 3 days approx or soon.

**Comment by machuwey** [comment]
@SoarinSkySagar Please write me a Dm in telegram if you can to confirm the assigment, you can find my contact at [t.me/strapexlabs](t.me/strapexlabs)

**Comment by Michaelkingsdev** [comment]
May I try my hand at this?

**Comment by SoarinSkySagar** [comment]
> @SoarinSkySagar Please write me a Dm in telegram if you can to confirm the assigment, you can find my contact at [t.me/strapexlabs](t.me/strapexlabs)

sure ser

**Comment by Kaminar-i** [comment]
Can I take on this
